travis:
  secure:
    BINSTAR_TOKEN: JLtZZzwYzPuMweF17hhWgjNOdA78S/cHzUuQvBycoFFNUfWLCXnrucFcRqiehFUVa/25UAgjZlX1e8dkyq6PlgqoaF8I1ssr4ud7Z8ep5+ab5JfxgTdwC77baKdiVwc6ZcP3G4Ua2j4Ss3Pj+HcyBsX7C/H6mq2BCONtIC7khjWmMXQ92KrFb5eAjZo4KTqKc0L/nj2Bw+X2TDsf65W/L/4xTVpV3cj/rKtvNPS4ULjIFo0B6mVDsWYCLgYODEBECA7RTRnA90bpnlgB/0zBMgV447uTsP1vFyKXdgS7Qe1p+C9Br65iWU2C7erpe1F+s+afqN10MD0cxWo+mh3SrquPNLLAgjU5eNzvL6j7BjVYXntfwQBwOe+DCnvy1bl+kTCac1jblDtCTjjLzwAwoCb8q29cXMY6CjQQtB5iBYD9hW2xfFbZ7SSxRxGysYNAykvx9kWLb7xqx9z5qe0P+Q+Z0seQAdy9ayGxq07BR00+Vm/XFpKZXZR1ZIYzg59qrCdM+apa0FfHeFBklGNPdYCFRo6/j6gDz+dsCueplqspyp3iHZXQLe+qfdP9W5PvOUwhWr8kOQk2CKaAi68wbxfx3uhA7H8aDBhP36zS77wlbL0uFrZYjWW/mCj5CE6Sa7TKcmJhwK+rD/RWqtCF/ZiJCN4xYoFdD6p5uJccNkE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
