travis:
  secure:
    BINSTAR_TOKEN: QC3krI+y+5Xy6yaAQuJsB7hLrGf/k1dc9z8h5DecCEca3h23ZToPyfC68VwdPl9AJ64dCMotCTtaWMiH8qe5LWWvDbjMra5KRCKcm17TW4WfMd28OCBRV1Ms+hcYprKn48ENfpKjOCPiWRr0xr6CNR+P6jt8pfs/eZdcjQoCFsbSbI+LQIXpC7+ozie74MAQoAkoWjB3beCSJuRsEtK2hksImOADME0/69fOjgNX6TH47OFOkPXwemgoIkou+5TcrO0U3RCqCwXwUjgKnDVqBa3lyQCSpCggm44qx4OjdSXU+b/qCATTGYFrnI+hINvTmLLFLI08ZEyhtBvUvPw5TOf6kSa/PsVfeyMPqpP6wtlTAflV6b1IJ3RyZPLyi6hztsAyn6xgWk9YeIiXKOXELN/uNk8DSSe3LzsXcEMog1N6709WowSGCYChlUkMoVn5sDCyy2ek+6ZtCIVuQqXTPOZXjli6MChgeXiBfHN2P3Pc18XGd43pVQ8+YV+Nflt1A7gKHDdvhKYamCNXj5oDVCodvTbfimJs/8hB4am7ndTLzdTZShja9591o8EHBlYMax+cScqvrXP/jYppnXgLQg6Q3/A/9PfukoaMuY/hGYtjXsBOBX949P4xMN9AM81nUfg/pNH9NC1jLKJCAzWqhQOyjtImRhiUDbytm8f3rws=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
